# Target Embedding Processing

In [23]:
import pandas as pd
import numpy as np

path = "./spose_embedding_66d_sorted.txt"
df = pd.DataFrame(np.loadtxt(path))
df = df.dropna(axis=1)
df_min = df.min().min()
df_max = df.max().max()
df = ((df - df_min) / (df_max - df_min))*100
df['image_name'] = pd.read_csv("./hebart66_embedding_rescaled.csv").iloc[:, 0]
df = df[['image_name'] + [col for col in df.columns if col != 'image_name']]
df

,image_name,0,1,2,3,4,5,6,7,8,...,56,57,58,59,60,61,62,63,64,65
0,aardvark_01b.jpg,0.341220,11.009447,85.825172,2.017321,3.539325,1.171418,1.554199,5.746191,5.657959,...,0.206361,4.010090,4.851254,1.019566,4.344110,2.895683,0.619276,1.941730,0.876354,4.133178
1,abacus_01b.jpg,34.561430,6.095580,1.599256,0.071981,2.274088,16.384406,23.314966,1.789315,7.448761,...,0.218143,0.981333,1.270298,2.377206,1.797705,5.291949,21.970696,3.703381,5.082176,1.499123
2,accordion_01b.jpg,32.230209,2.052996,0.607386,5.391949,1.776888,12.140417,18.484304,10.454821,4.072150,...,0.256890,2.360300,3.208472,1.103346,0.549976,1.874761,2.102312,0.934895,0.399195,0.706830
3,acorn_01b.jpg,12.183742,40.210646,25.002625,2.881494,35.759315,0.587310,13.291280,0.569317,1.475594,...,4.005267,7.394161,7.540498,1.532976,0.587954,2.289763,1.474941,3.828291,0.530486,2.973921
4,air_conditioner_01b.jpg,33.532741,1.958939,0.240833,8.661669,4.434921,50.014353,0.713751,12.044481,3.880265,...,0.977536,2.600658,3.313508,0.688709,3.840480,17.434839,1.009810,1.212375,0.410518,0.543100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1849,yoke_01s.jpg,51.607612,6.172904,18.222743,11.282825,1.426970,8.528125,13.789661,1.326499,5.578982,...,2.793201,1.625961,2.209912,1.333829,1.197319,1.459878,1.420475,0.713718,2.710566,1.256583
1850,yolk_01b.jpg,0.257955,76.454118,19.712390,1.243027,3.707726,0.639672,0.762570,0.303541,0.372460,...,0.345086,0.913928,7.157405,0.592901,0.330611,1.525518,4.339419,0.673683,0.682231,1.003286
1851,zebra_01b.jpg,2.140060,1.833954,89.369396,2.784000,7.251922,2.984810,1.754516,14.924283,4.133019,...,0.098185,2.203939,0.616640,0.739664,1.668679,1.162892,1.020552,0.612812,1.500188,0.796950
1852,zipper_01b.jpg,70.946833,1.219540,1.704311,41.355544,0.429764,1.997170,2.551451,4.813398,17.133789,...,1.715092,0.737487,2.915487,0.581908,0.565508,3.826156,5.268929,0.685031,1.432849,0.731687
1853,zucchini_01b.jpg,1.725352,61.098990,15.315227,0.582387,50.704322,1.935637,0.411583,1.373649,0.797375,...,0.611148,0.541572,1.116809,1.594353,0.777786,1.749629,1.464458,0.150395,0.707131,0.265158

In [24]:
df.to_csv("hebart66_embedding_rescaled100.csv", index=True)

Drop the 48 Validation Sample set

In [ ]:
from scipy.io import loadmat
sample48 = pd.DataFrame(loadmat("./words48.mat")['words48'])
sample48 = sample48.astype(str).apply(lambda x: x.str.strip('[]'))
sample48 = sample48.applymap(lambda x: x[1:-1])
sample48 = sample48.replace(' ', '_', regex=True)
sample48 = sample48.replace('camera', 'camera1', regex=True)
sample48 = sample48.replace('file', 'file1', regex=True)

print(np.array(sample48).tolist())

                 0
0            pizza
1           beaver
2        macadamia
3        tarantula
4          clothes
5          doormat
6           hammer
7        mistletoe
8        washcloth
9            drain
10         furnace
11             tea
12         chariot
13         coaster
14       music_box
15     rolling_pin
16            knob
17       bookshelf
18      candelabra
19           table
20  metal_detector
21          bumper
22          turban
23        flagpole
24    plaster_cast
25            tuba
26         camera1
27          rudder
28          canvas
29            dice
30         toolbox
31         trigger
32      bowler_hat
33      headphones
34           file1
35           bench
36           navel
37        canister
38           tiara
39       hopscotch
40          trophy
41    punching_bag
42             jet
43       telegraph
44             bag
45          laptop
46    tape_measure
47          bucket

In [26]:
df_train = df[~df['image_name'].str[:-8].isin(sample48[0].values.tolist())]
df_train

,image_name,0,1,2,3,4,5,6,7,8,...,56,57,58,59,60,61,62,63,64,65
0,aardvark_01b.jpg,0.341220,11.009447,85.825172,2.017321,3.539325,1.171418,1.554199,5.746191,5.657959,...,0.206361,4.010090,4.851254,1.019566,4.344110,2.895683,0.619276,1.941730,0.876354,4.133178
1,abacus_01b.jpg,34.561430,6.095580,1.599256,0.071981,2.274088,16.384406,23.314966,1.789315,7.448761,...,0.218143,0.981333,1.270298,2.377206,1.797705,5.291949,21.970696,3.703381,5.082176,1.499123
2,accordion_01b.jpg,32.230209,2.052996,0.607386,5.391949,1.776888,12.140417,18.484304,10.454821,4.072150,...,0.256890,2.360300,3.208472,1.103346,0.549976,1.874761,2.102312,0.934895,0.399195,0.706830
3,acorn_01b.jpg,12.183742,40.210646,25.002625,2.881494,35.759315,0.587310,13.291280,0.569317,1.475594,...,4.005267,7.394161,7.540498,1.532976,0.587954,2.289763,1.474941,3.828291,0.530486,2.973921
4,air_conditioner_01b.jpg,33.532741,1.958939,0.240833,8.661669,4.434921,50.014353,0.713751,12.044481,3.880265,...,0.977536,2.600658,3.313508,0.688709,3.840480,17.434839,1.009810,1.212375,0.410518,0.543100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1849,yoke_01s.jpg,51.607612,6.172904,18.222743,11.282825,1.426970,8.528125,13.789661,1.326499,5.578982,...,2.793201,1.625961,2.209912,1.333829,1.197319,1.459878,1.420475,0.713718,2.710566,1.256583
1850,yolk_01b.jpg,0.257955,76.454118,19.712390,1.243027,3.707726,0.639672,0.762570,0.303541,0.372460,...,0.345086,0.913928,7.157405,0.592901,0.330611,1.525518,4.339419,0.673683,0.682231,1.003286
1851,zebra_01b.jpg,2.140060,1.833954,89.369396,2.784000,7.251922,2.984810,1.754516,14.924283,4.133019,...,0.098185,2.203939,0.616640,0.739664,1.668679,1.162892,1.020552,0.612812,1.500188,0.796950
1852,zipper_01b.jpg,70.946833,1.219540,1.704311,41.355544,0.429764,1.997170,2.551451,4.813398,17.133789,...,1.715092,0.737487,2.915487,0.581908,0.565508,3.826156,5.268929,0.685031,1.432849,0.731687
1853,zucchini_01b.jpg,1.725352,61.098990,15.315227,0.582387,50.704322,1.935637,0.411583,1.373649,0.797375,...,0.611148,0.541572,1.116809,1.594353,0.777786,1.749629,1.464458,0.150395,0.707131,0.265158

In [27]:
df_train.to_csv("hebart66_embedding_rescaled100_1806train.csv", index=True)

In [28]:
df_val = df[df['image_name'].str[:-8].isin(sample48[0].values.tolist())]
df_val

,image_name,0,1,2,3,4,5,6,7,8,...,56,57,58,59,60,61,62,63,64,65
54,bag_01b.jpg,19.739508,21.198930,0.965733,61.468153,11.073226,9.788339,9.625351,15.912599,2.198941,...,0.338231,1.223847,0.397648,1.447020,1.193706,1.867710,4.865227,0.772874,0.633689,1.146184
107,beaver_01b.jpg,1.351147,3.982135,91.049569,0.348649,8.929281,0.727055,1.539169,1.017233,4.268899,...,0.835306,1.310193,0.634133,1.074213,1.590090,0.353474,0.348709,6.902653,0.678244,0.898877
120,bench_01b.jpg,19.191424,1.605347,13.517206,6.407105,20.713978,37.498421,9.768035,12.167288,4.310959,...,1.280562,2.321272,0.645485,0.518135,3.398300,1.392657,1.299114,0.210752,1.714176,0.614359
167,bookshelf_01b.jpg,29.417111,5.513788,2.725984,5.742776,3.065285,52.055107,9.610171,3.903207,3.200359,...,1.890110,2.889659,1.730980,2.638301,1.720632,1.173678,1.655648,0.723997,0.482410,0.609844
178,bowler_hat_01b.jpg,21.006404,0.311069,5.878286,45.166940,0.794244,4.213119,24.824021,5.320632,22.718669,...,13.707117,1.680679,0.383178,0.357866,6.873350,0.385852,0.671290,1.025783,1.914086,1.177994
209,bucket_01b.jpg,26.124471,2.771364,1.931005,3.124801,1.329754,10.097789,0.109989,7.907720,0.745661,...,0.283587,0.814655,36.743175,3.109632,5.820576,0.406807,0.723769,0.262547,1.431520,1.408017
219,bumper_01b.jpg,42.286053,0.446922,4.622603,0.733333,14.656451,31.504313,0.963055,34.650707,1.912529,...,1.716308,0.761756,1.203368,0.402542,1.558329,0.887038,2.210563,0.615473,1.227731,0.369118
246,camera1_01b.jpg,39.808612,3.102163,9.338561,6.669288,8.022120,2.425891,9.244413,16.774327,9.019348,...,0.510128,2.298459,1.525314,0.967909,1.262022,2.613879,3.471924,2.027651,2.312595,0.853736
252,candelabra_01b.jpg,48.694809,18.335304,0.171196,6.274163,7.606161,14.422245,49.816305,1.365530,1.281210,...,0.553680,0.457711,1.420290,1.103494,0.265012,2.059565,0.410294,0.879395,2.148643,0.814729
259,canister_01b.jpg,43.566395,36.196946,2.036390,8.728901,3.804956,17.372505,17.987870,0.997213,2.333764,...,2.583639,6.081209,1.194126,1.015839,1.585392,3.409781,1.960516,3.011017,1.428132,0.680481
264,canvas_01b.jpg,27.260113,2.213626,0.660178,10.343679,1.354767,43.214296,6.028725,4.570220,1.397167,...,2.814301,2.932934,2.612632,4.102161,0.597166,2.702038,4.190940,0.596741,0.869343,4.626708
309,chariot_01b.jpg,18.690386,0.067641,30.365279,1.925161,0.241245,1.544309,27.743044,48.054771,27.479074,...,3.129329,0.343162,4.223562,1.192599,0.996608,0.695131,0.740174,0.104051,0.713936,1.509056
361,clothes_01b.jpg,17.074035,5.927117,0.559973,64.757009,0.550780,20.667788,10.700128,6.312492,27.745907,...,0.405871,2.788111,1.759666,0.748589,1.264117,0.413484,0.788253,1.119951,3.678706,0.565343
368,coaster_01b.jpg,23.978785,28.080495,0.083978,14.618301,1.985131,6.954676,19.797620,6.148218,3.669883,...,1.097101,1.981868,1.515802,4.456042,1.426552,0.362765,0.162490,1.822113,6.636008,0.562839
486,dice_01s.jpg,26.038370,4.410685,0.310135,0.620756,0.903015,8.475021,12.745297,0.502101,1.109671,...,4.245657,2.745416,1.359314,1.292441,22.500962,0.270426,15.272038,3.109494,10.510806,0.273861
511,doormat_01b.jpg,27.668616,1.333949,3.763505,31.512812,2.485024,43.984693,0.406343,4.048382,0.720453,...,0.733039,1.749599,0.673369,8.979061,1.360710,2.850224,0.744578,24.034998,0.826772,3.785740
515,drain_01b.jpg,43.392993,1.394979,2.389817,0.048387,2.409937,13.028763,1.558880,5.108158,2.361691,...,2.506592,1.099434,3.552829,2.002353,0.792178,5.259372,1.685407,4.429198,2.578543,0.171680
583,file1_01b.jpg,61.739690,2.952721,2.684359,1.407977,6.097623,2.231967,0.898240,11.686546,1.793592,...,1.294690,1.130261,1.865216,1.559576,0.994875,2.909465,3.094679,0.476242,1.183196,1.504961
606,flagpole_01s.jpg,31.938026,0.239412,1.902678,7.612847,1.504684,11.607264,3.346109,12.997811,3.562859,...,1.095726,0.189482,2.614009,0.924575,0.667712,4.663053,0.378685,4.312128,1.181178,1.636396
651,furnace_01b.jpg,30.699743,15.352041,0.722855,2.264861,1.356180,24.706479,4.186076,12.199566,1.211456,...,0.223142,1.581620,14.166683,4.337344,0.374620,4.642744,1.316757,0.294948,0.492478,2.351991
741,hammer_01b.jpg,74.324402,2.189895,0.914380,4.963368,4.887020,5.686995,2.061556,3.859596,3.829375,...,2.502977,1.669553,2.046180,0.425683,0.829301,6.109572,1.078585,1.353046,0.216303,1.923255
766,headphones_01b.jpg,44.853429,1.931738,1.174505,19.997033,2.094404,5.481991,1.030174,8.544079,11.766424,...,0.437455,1.019029,0.637471,0.114636,0.842147,1.602926,1.115010,1.576036,1.356918,0.799451
796,hopscotch_01b.jpg,4.308666,0.954249,18.293951,1.421681,0.417679,12.432944,0.160435,7.830021,42.178532,...,3.793545,3.759322,4.558289,6.455542,4.336874,0.574021,13.163980,0.793003,0.376079,4.087781
847,jet_01b.jpg,37.912958,1.397590,6.044436,0.386762,0.708978,3.712684,0.319448,51.323954,3.302718,...,2.530710,0.764661,0.598662,1.035197,0.392073,3.392568,1.014148,1.261972,1.745763,2.581166
882,knob_01b.jpg,43.728955,1.948009,1.455159,6.281604,2.766253,20.687058,26.089413,3.519433,0.764651,...,2.103352,1.488267,5.093806,0.281517,13.273517,7.014052,2.606593,1.560963,0.972457,1.181405
897,laptop_01b.jpg,32.845098,0.588530,0.444125,1.718532,0.185086,23.232567,12.039542,11.442573,7.437911,...,2.349407,0.469222,1.858801,0.387587,2.098749,1.007076,1.361236,1.581413,0.215670,1.405337
951,macadamia_01b.jpg,0.175553,71.531011,11.933544,2.671233,25.394823,1.048132,0.678898,0.271861,0.372288,...,0.363602,1.691655,2.450691,2.626235,6.709733,0.598063,0.667009,3.353153,0.804669,2.255038
996,metal_detector_01b.jpg,49.060686,0.796704,16.076637,1.382606,0.556339,1.019084,2.130817,5.557093,30.463420,...,0.649140,1.588818,1.309504,1.758516,0.538714,0.148073,0.887271,1.532364,3.800605,18.243188
1007,mistletoe_01b.jpg,0.267086,29.419963,10.516818,15.101221,60.165025,5.128098,23.958196,2.521372,0.935418,...,1.474877,8.883826,3.139614,0.254741,0.720259,1.361368,0.926956,13.546632,2.060121,1.608356
1041,music_box_01b.jpg,36.083112,7.333954,1.682381,7.632826,2.530022,8.400962,39.805782,5.634566,2.365815,...,0.772652,0.714310,20.038820,3.947183,2.462073,4.839025,1.694129,1.443546,0.945187,3.185338
1052,navel_01b.jpg,0.848324,11.196411,20.691188,10.590317,0.749659,0.855593,1.347366,0.171048,41.472277,...,10.156329,0.389973,0.398336,1.029405,1.881106,1.103066,0.326257,0.437758,3.771607,1.357867
1192,pizza_01b.jpg,0.040818,82.180270,5.129200,0.342989,1.143842,0.242650,1.375374,2.086829,2.315461,...,0.192906,0.276354,2.491111,0.480851,0.745000,1.195443,1.029029,1.055646,1.338602,2.038748
1195,plaster_cast_01b.jpg,12.591710,1.664963,12.636886,23.254945,0.401962,3.341157,3.189459,8.297896,42.186888,...,28.031645,0.696088,0.814574,16.493013,7.783226,13.145289,1.241912,2.755523,2.849737,1.951634
1256,punching_bag_01b.jpg,31.397109,4.348809,2.308599,23.006609,6.145209,4.082155,0.374387,2.756857,11.456370,...,0.491935,4.998925,1.518867,1.258965,36.879802,1.314284,1.553336,1.308282,3.181921,1.976670
1328,rolling_pin_01b.jpg,35.088227,43.744901,1.962273,6.410465,2.184563,3.538881,7.918149,2.128874,2.598542,...,2.404716,3.126540,0.811863,3.396142,3.081345,2.643622,1.155990,0.588295,1.757280,0.843733
1339,rudder_01b.jpg,37.544196,5.922858,5.121294,11.650289,1.009891,15.989506,12.534920,23.751245,1.541144,...,2.552992,0.866828,5.604989,11.094067,3.823663,1.926228,2.985180,1.985443,0.262883,0.967223
1608,table_01b.jpg,32.069551,19.647337,0.033206,6.026342,0.071441,51.261794,11.764309,4.776310,2.082367,...,0.716031,0.152979,0.352083,1.080381,1.673312,0.656431,4.770846,1.033372,0.176716,0.985361
1623,tape_measure_01b.jpg,50.422447,0.614961,2.272937,3.601959,1.165130,13.212380,2.755284,7.436158,2.578813,...,1.572175,0.727655,0.751157,9.249273,1.010700,1.192600,56.159846,1.786485,2.150583,1.317146
1626,tarantula_01b.jpg,2.124433,2.885719,68.755384,3.215477,11.377061,1.768419,1.334212,0.863935,4.671783,...,0.567572,2.012773,0.444472,1.185281,0.989735,1.015517,1.135721,4.650351,5.119790,0.038735
1631,tea_01b.jpg,2.596625,55.010635,1.319594,9.176923,19.294777,4.436228,17.691005,1.321764,9.244365,...,1.292334,9.705763,5.074999,0.381252,1.294716,0.689100,5.483420,1.570993,16.450868,0.361322
1638,telegraph_01s.jpg,61.693377,5.914145,3.474078,1.073188,1.176101,0.259996,21.213094,3.672016,1.104033,...,13.146040,0.466024,1.816654,0.581838,0.449444,2.786625,12.803262,2.504774,3.579504,0.420475
1655,tiara_01b.jpg,36.107647,1.493680,3.692025,21.469719,0.185816,1.703238,51.363825,0.405219,24.955577,...,1.720398,7.333154,0.606545,1.471914,1.504480,2.883385,1.251742,1.094496,2.467817,1.721392
1677,toolbox_01b.jpg,54.922965,0.855833,0.923138,3.122715,0.311370,10.294094,0.583530,17.988885,2.903489,...,9.572617,0.464787,0.832805,0.466849,4.293434,0.280144,1.720022,0.648800,0.656986,0.555858
1713,trigger_01s.jpg,57.016805,0.207667,4.585534,0.770994,2.739302,0.207816,2.029732,12.824258,5.552717,...,1.937684,2.746393,1.537862,1.478065,2.380476,3.364789,0.418864,0.936327,13.464833,1.358844
1717,trophy_01b.jpg,49.464850,3.709667,1.725861,2.817959,2.669267,2.407254,41.117004,15.091638,8.870951,...,2.065877,2.692239,1.707811,2.518882,1.652741,1.040475,0.320674,2.119494,1.527726,0.350107
1723,tuba_01b.jpg,48.704748,6.535005,2.514311,1.804601,0.390533,0.282671,37.224680,10.699907,5.931036,...,1.407835,0.882797,7.967734,0.572219,1.187136,0.787040,1.399282,0.963086,4.094759,2.458474
1730,turban_01b.jpg,3.532169,10.005822,18.622213,44.189962,1.169923,0.536543,22.876779,3.841993,42.953580,...,0.168363,1.181862,47.575000,0.630320,0.460588,0.679976,2.055304,2.015428,1.806521,0.875910
1783,washcloth_01b.jpg,10.258176,22.386851,2.583974,57.723912,4.973370,25.545470,5.084556,1.397576,3.709235,...,1.808977,0.278131,6.591927,23.480504,3.473040,4.616013,2.416539,12.543901,0.098682,0.816772

In [29]:
df_val.to_csv("hebart66_embedding_rescaled100_48val.csv", index=True)

# Prompt

In [68]:
df = pd.read_csv("./labels66_pairs.csv", header=None)
classnames66 = np.array(df).tolist()
classnames66

[['metallic; artificial', 'nonmetallic; natural'],
 ['food-related', 'non-food-related'],
 ['animal-related', 'non-animal-related; artificial; inorganic'],
 ['textile', 'non-textile'],
 ['plant-related', 'non-plant-related'],
 ['house-related; furnishing-related',
  'non-house-related; non-furnishing-related; outdoors-related'],
 ['valuable; precious', 'non-valuable; inexpensive; cheap'],
 ['transportation; movement-related', 'non-transportation; movement-related'],
 ['body; people-related', 'non-body; people-related'],
 ['wood-related; brown', 'non-wood-related; non-brown'],
 ['electronics; technology', 'non-electronics; technology'],
 ['colorful; playful', 'monotone; dull'],
 ['outdoors', 'non-outdoors'],
 ['circular; round', 'non-circular; angular'],
 ['paper-related; flat', 'non-paper-related; bumpy'],
 ['hobby-related; game-related; playing-related',
  'non-hobby-related; non-game-related; non-playing-related'],
 ['tools-related; handheld; elongated',
  'non-tools-related; non-handheld; shortened'],
 ['fluid-related; drink-related', 'solid-related; non-fluid-related'],
 ['water-related', 'dry; non-water-related'],
 ['oriented; many; plenty', 'non-oriented; few; scarce'],
 ['powdery; earth-related; waste-related',
  'non-powdery; non-earth-related; non-waste-related'],
 ['white', 'black; dark'],
 ['coarse-scale pattern; many things', 'non-coarse-scalepattern; few; scarce'],
 ['red', 'non-red'],
 ['long; thin', 'short; thick'],
 ['weapon-related; war-related; dangerous',
  'non-weapon-related; non-war-related; peaceful'],
 ['black', 'non-black; white'],
 ['household-related', 'non-household-related'],
 ['feminine', 'non-feminine; masculine'],
 ['body-part-related', 'non-body-part-related'],
 ['tubular', 'non-tubular'],
 ['music-related; hearing-related; hobby-related; loud',
  'non-music-related; non-hearing-related; non-hobby-related; silent'],
 ['grid-related; grating-related', 'non-grid-related; non-grating-related'],
 ['repetitive; spiky', 'diverse; dull'],
 ['construction-related; craftsmanship-related; housework-related',
  'non-physical-work-related'],
 ['spherical; voluminous', 'angular; small'],
 ['string-related; stringy; curved', 'non-string-related; straight'],
 ['seating; standing; lying-related',
  'non-seating; non-standing; non-lying-related'],
 ['flying-related; sky-related', 'ground-related; non-flying-related'],
 ['bug-related; non-mammalian; disgusting',
  'non-bug-related; mammalian; pleasant'],
 ['transparent; shiny; crystalline', 'opaque; matte; frosted'],
 ['sand-colored', 'non-sand-colored'],
 ['green', 'non-green'],
 ['bathroom-related; wetness-related', 'non-bathroom-related; dry'],
 ['yellow', 'non-yellow'],
 ['heat-related; fire-related; light-related', 'cold-related; dark-related'],
 ['beams-related; mesh-related', 'non-beams-related; non-mesh-related'],
 ['foot-related; walking-related', 'non-foot-related; non-walking-related'],
 ['box-related; container', 'non-box-related; non-container'],
 ['stick-shaped; container', 'non-stick-shaped; non-container'],
 ['head-related', 'non-head-related'],
 ['upright; elongated; volumous', 'non-upright; short; small'],
 ['pointed; spiky', 'non-pointed; blunt'],
 ['child-related; toy-related; cute', 'mature; adult-like'],
 ['farm-related; historical', 'non-farm-related; contemporary'],
 ['seeing-related', 'non-seeing-related; blind'],
 ['medicine-related; health-related',
  'non-medicine-related; non-health-related'],
 ['sweet; dessert-related', 'non-sweet; non-dessert-related'],
 ['orange', 'non-orange'],
 ['thin; flat; wrapping', 'thick; bumpy; non-wrapping'],
 ['cylindrical; conical; cushioning', 'triangular; angular; hardening'],
 ['coldness-related; winter-related', 'warmness-related; non-winter-related '],
 ['measurement-related; numbers-related',
  'non-measurement-related; non-numerical'],
 ['fluffy; soft', 'non-fluffy; rough'],
 ['masculine', 'non-masculine; feminine'],
 ['fine-grained; pattern', 'non-fine-grained; plain']]

# Image Set Split

In [72]:
name_df = pd.read_csv("./hebart49_embedding_rescaled_1806train.csv").iloc[:, 0]
name_df

0              aardvark_01b.jpg
1                abacus_01b.jpg
2             accordion_01b.jpg
3                 acorn_01b.jpg
4       air_conditioner_01b.jpg
                 ...
1801               yoke_01s.jpg
1802               yolk_01b.jpg
1803              zebra_01b.jpg
1804             zipper_01b.jpg
1805           zucchini_01b.jpg
Name: image_name, Length: 1806, dtype: object

In [76]:
# import os
# import shutil

# output_path = './HebartImageTrain1806'
# os.makedirs(output_path, exist_ok=True)

# for i, name in enumerate(name_df):
#     source_path = f'/home/wallacelab/CLIP-IQA/CLIP-HBA/Data/HebartImages3/{name}'
#     destination_path = f'{output_path}/{name}'
#     shutil.copy(source_path, destination_path)

In [4]:
import pandas as pd
name_df = pd.read_csv("./hebart66_embedding_rescaled_48val.csv")['image_name']
name_df

0                bag_01b.jpg
1             beaver_01b.jpg
2              bench_01b.jpg
3          bookshelf_01b.jpg
4         bowler_hat_01b.jpg
5             bucket_01b.jpg
6             bumper_01b.jpg
7            camera1_01b.jpg
8         candelabra_01b.jpg
9           canister_01b.jpg
10            canvas_01b.jpg
11           chariot_01b.jpg
12           clothes_01b.jpg
13           coaster_01b.jpg
14              dice_01s.jpg
15           doormat_01b.jpg
16             drain_01b.jpg
17             file1_01b.jpg
18          flagpole_01s.jpg
19           furnace_01b.jpg
20            hammer_01b.jpg
21        headphones_01b.jpg
22         hopscotch_01b.jpg
23               jet_01b.jpg
24              knob_01b.jpg
25            laptop_01b.jpg
26         macadamia_01b.jpg
27    metal_detector_01b.jpg
28         mistletoe_01b.jpg
29         music_box_01b.jpg
30             navel_01b.jpg
31             pizza_01b.jpg
32      plaster_cast_01b.jpg
33      punching_bag_01b.jpg
34       rolling_pin_01b.jpg
35            rudder_01b.jpg
36             table_01b.jpg
37      tape_measure_01b.jpg
38         tarantula_01b.jpg
39               tea_01b.jpg
40         telegraph_01s.jpg
41             tiara_01b.jpg
42           toolbox_01b.jpg
43           trigger_01s.jpg
44            trophy_01b.jpg
45              tuba_01b.jpg
46            turban_01b.jpg
47         washcloth_01b.jpg
Name: image_name, dtype: object

In [5]:
# import os
# import shutil

# output_path = './ThingsVal48'
# os.makedirs(output_path, exist_ok=True)

# for i, name in enumerate(name_df):
#     source_path = f'./Things1854/{name}'
#     destination_path = f'{output_path}/{name}'
#     shutil.copy(source_path, destination_path)